spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nnbc_qlns
    username: root
    password: Tropicalcolor26@
    maximumPoolSize: 30

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  #    show-sql: true
  #    properties:
  #      hibernate.format_sql: true



server:
  port: 8080

healthcheck:  #kiem tra xem app da hoat dong chua
  endpoints:
  apiNames:
  dbConnections:
#    - jdbc:mysql://fdev02.cdonp287nkta.ap-southeast-1.rds.amazonaws.com:3306/cfcb_passenger

logging:
  level:
    ROOT: info


management:
  endpoints:
    web:
      exposure:
        include: "loggers"

